name: "Test and lint the branch"

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  on-push:
    uses: bactions/workflows/.github/workflows/on-push-go.yml@on-push-additional-environment
    with:
      go-generate-extra-tools: "node"
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
